import{a as w,S,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(e){if(e.ep)return;e.ep=!0;const i=o(e);fetch(e.href,i)}})();const q="https://pixabay.com/api/",P="51538469-8b3be560c440e4726340ee2f6",R=15;async function h(r,t){const o={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:R};return(await w.get(q,{params:o})).data}const y=document.querySelector(".gallery"),s=document.querySelector(".loader-wrapper"),n=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=x(r);y.insertAdjacentHTML("beforeend",t),E.refresh()}function A(){y.innerHTML=""}function b(){s==null||s.classList.remove("is-hidden")}function v(){s==null||s.classList.add("is-hidden")}function O(){n==null||n.classList.remove("is-hidden")}function u(){n==null||n.classList.add("is-hidden")}function x(r){return r.map(({webformatURL:t,largeImageURL:o,tags:a,likes:e,views:i,comments:c,downloads:L})=>`
        <li class="gallery-item">
          <a href="${o}" class="gallery-link">
            <img src="${t}" alt="${a}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><b>Likes</b><span>${e}</span></div>
            <div class="image-info-item"><b>Views</b><span>${i}</span></div>
            <div class="image-info-item"><b>Comments</b><span>${c}</span></div>
            <div class="image-info-item"><b>Downloads</b><span>${L}</span></div>
          </div>
        </li>
      `).join("")}const g=document.querySelector(".form"),H=document.querySelector(".load-more");let m="",d=1,f=0;g.addEventListener("submit",async r=>{r.preventDefault();const t=g.elements["search-text"].value.trim();if(!t){l.info({message:"Please enter a search term.",position:"topRight"});return}m=t,d=1,A(),u(),b();try{const o=await h(m,d);if(f=o.totalHits,!o.hits.length){l.warning({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}p(o.hits),o.hits.length<15||f<=15?u():O()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}});H.addEventListener("click",async()=>{d++,b();try{const r=await h(m,d);p(r.hits),document.querySelectorAll(".gallery-item").length>=f&&(u(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch{l.error({message:"Failed to load more images.",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
